name: beer
channels:
  - anaconda
  - defaults
dependencies:
  - cairo=1.14.12
  - expat=2.2.6
  - fontconfig=2.13.0
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.12
  - harfbuzz=1.8.8
  - icu=58.2
  - libiconv=1.15
  - libxml2=2.9.8
  - pango=1.42.4
  - pcre=8.42
  - pixman=0.34.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - bokeh=1.0.0
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - cffi=1.11.5
  - cycler=0.10.0
  - decorator=4.3.0
  - entrypoints=0.2.3
  - freetype=2.9.1
  - graphviz=2.40.1
  - intel-openmp=2019.0
  - ipykernel=5.1.0
  - ipython=7.0.1
  - ipython_genutils=0.2.0
  - jedi=0.13.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - jupyterlab=0.35.2
  - jupyterlab_server=0.2.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libpng=1.6.35
  - libsodium=1.0.16
  - libtiff=4.0.9
  - markupsafe=1.0
  - mistune=0.8.4
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - natsort=5.4.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.8.2
  - notebook=5.7.0
  - numpy=1.15.2
  - numpy-base=1.15.2
  - olefile=0.46
  - openssl=1.1.1
  - packaging=18.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=10.0.1
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.6
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.2.0
  - pyparsing=2.2.2
  - python=3.7.1
  - python-dateutil=2.7.3
  - python-graphviz=0.8.4
  - pytz=2018.7
  - pyyaml=3.13
  - pyzmq=17.1.2
  - readline=7.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.4.3
  - simplegeneric=0.8.1
  - six=1.11.0
  - sqlite=3.25.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11

